### ISSUE TITLE
Admin rights causes crash of the app

### ISSUE THREAD

**Issue by victorct** [ravibpatel/AutoUpdater.NET#119]
I have implemented the library, when I run my app in Debug mode everything works fine and it detects the new version and installs it, but when I'm in Release mode it crashes the app with the next error:

```
Unhandled Exception:
System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at AutoUpdaterDotNET.UpdateForm.UseLatestIE() in C:\Users\Ravi Patel\Documents\Visual Studio 2017\Projects\AutoUpdater.NET\AutoUpdater.NET\UpdateForm.cs:line 78
   at AutoUpdaterDotNET.UpdateForm..ctor() in C:\Users\Ravi Patel\Documents\Visual Studio 2017\Projects\AutoUpdater.NET\AutoUpdater.NET\UpdateForm.cs:line 19
   at AutoUpdaterDotNET.AutoUpdater.ShowUpdateForm() in C:\Users\Ravi Patel\Documents\Visual Studio 2017\Projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.cs:line 262
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

The error happens at this [line](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/UpdateForm.cs#L78)  when trying to get the process.

I have in my manifest the execution level `asInvoker` but it didn't work.

After the error happens, it closes the app.

**Comment by ravibpatel** [comment]
@victorct  Still have this problem?

**Comment by victorct** [comment]
@ravibpatel  Yep.

**Comment by ravibpatel** [comment]
@victorct I can't reproduce the issue. Do you get this error on other PC's too?
