### ISSUE TITLE
Error Message When Downloading

### ISSUE THREAD

**Issue by ahmadstout** [ravibpatel/AutoUpdater.NET#126]
System.DivideByZeroException: Attempted to divide by zero.
   at AutoUpdaterDotNET.DownloadUpdateDialog.OnDownloadProgressChanged(Object sender, DownloadProgressChangedEventArgs e) in c:\projects\AutoUpdater.NET\AutoUpdater.NET\DownloadUpdateDialog.cs:line 60
   at System.Net.WebClient.OnDownloadProgressChanged(DownloadProgressChangedEventArgs e)
   at System.Net.WebClient.ReportDownloadProgressChanged(Object arg)

**Comment by ravibpatel** [comment]
@ahmadstout Fixed in the latest release.

**Comment by ahmadstout** [comment]
@ravibpatel 
Thank You
