### ISSUE TITLE
App timed out but cant catch it.

### ISSUE THREAD

**Issue by KristianLake** [ravibpatel/AutoUpdater.NET#151]
Hi i have a link that times out but i cant seem to catch the error. 

    at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
      at AutoUpdaterDotNET.AutoUpdater.BackgroundWorkerOnRunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs runWorkerCompletedEventArgs)
      at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

Its just a standard timeout error. How do i tell the updater to continue if it times out? :)

**Comment by ravibpatel** [comment]
@topproto Currently it doesn't retry when it times out. But you can check if it encounters a network error and retries it again by handling update logic manually as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).
