### ISSUE TITLE
ZipExtractor crashes with "path not found"

### ISSUE THREAD

**Issue by fritz-net** [ravibpatel/AutoUpdater.NET#154]
This happens in an C# WPF project. With custom `CheckForUpdateEvent` and also the default window

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): Das System kann den angegebenen Pfad nicht finden
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ZipExtractor.FormMain.<>c__DisplayClass2_0.<FormMain_Shown>b__2(Object o, RunWorkerCompletedEventArgs eventArgs)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ZipExtractor
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Users/xxx/AppData/Local/Temp/ZipExtractor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2563.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by ravibpatel** [comment]
@fritz-net Can you give me URL of your XML file? I tested it and it works fine for me in WPF application.

**Comment by fritz-net** [comment]
@ravibpatel, no sorry, it's an internal Jenkins Build server where i get my xml from (which is fetched correctly since i get the information from it about newer versions)

Here is the content of the XML file:
```
<?xml version="1.0" encoding="UTF-8"?>
<item>
  <version>2.2.0.89</version>
  <url>http://xxx:8080/job/xxx/job/xxx/job/master/lastSuccessfulBuild/artifact/xxx.zip</url>
  <mandatory>false</mandatory>
</item>
```

**Comment by fritz-net** [comment]
@ravibpatel, i tried this with your example and also with a folder directly on C. The issue seams to come when I start my program from a networkdrive even if the downloaddir is on a local drive.

**Comment by ravibpatel** [comment]
@fritz-net While running from network drive I encountered [this problem](https://stackoverflow.com/questions/5168880/error-creating-the-web-proxy-specified-in-the-system-net-defaultproxy-configur).

**Comment by fritz-net** [comment]
@ravibpatel, no i had no problem. I develop on the network drive and also started the built application from the network directly -> no issues

for me the problem is solved since now I know a workaround (start locally)

**Comment by Traderain** [comment]
This happens to me as well.
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at AutoUpdaterDotNET.DownloadUpdateDialog.WebClientOnDownloadFileCompleted(Object sender, AsyncCompletedEventArgs asyncCompletedEventArgs) in c:\projects\AutoUpdater.NET\AutoUpdater.NET\DownloadUpdateDialog.cs:line 194
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WolvenKit
    Assembly Version: 0.3.0.1
    Win32 Version: 0.3.0.1
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/WolvenKit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
WolvenKit.CR2W
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/WolvenKit.CR2W.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3081.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Dfust.Hotkeys
    Assembly Version: 1.2.6206.24906
    Win32 Version: 1.2.6206.24906
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/Dfust.Hotkeys.DLL
----------------------------------------
Dfust.Hotkeys.Util
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/Dfust.Hotkeys.Util.DLL
----------------------------------------
Gma.System.MouseKeyHook
    Assembly Version: 5.4.0.0
    Win32 Version: 5.4.0.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/Gma.System.MouseKeyHook.DLL
----------------------------------------
AutoUpdater.NET
    Assembly Version: 1.4.10.0
    Win32 Version: 1.4.10.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/AutoUpdater.NET.DLL
----------------------------------------
WolvenKit.W3Strings
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/WolvenKit.W3Strings.DLL
----------------------------------------
WolvenKit.Bundles
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/WolvenKit.Bundles.EXE
----------------------------------------
WolvenKit.Interfaces
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/WolvenKit.Interfaces.DLL
----------------------------------------
WolvenKit.Cache
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/WolvenKit.Cache.EXE
----------------------------------------
WolvenKit.Wwise
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/WolvenKit.Wwise.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.2.21924
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/Newtonsoft.Json.DLL
----------------------------------------
protobuf-net
    Assembly Version: 2.3.13.0
    Win32 Version: 2.3.13.0
    CodeBase: file:///C:/Users/bence.hambalko/Documents/Repos/Wolven-kit/WolvenKit/bin/Debug/protobuf-net.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3081.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by ravibpatel** [comment]
@Traderain Are you trying to update the app on the network drive?

**Comment by Traderain** [comment]
Its installed to desktop and the update is on github releases.

**Comment by ravibpatel** [comment]
@Traderain Can you give me URL of your XML file?

**Comment by Traderain** [comment]
@ravibpatel yes, that seems to work. Could you fix the nuget package?

**Comment by ravibpatel** [comment]
@Traderain I will fix it asap. Thanks for reporting it.

**Comment by ravibpatel** [comment]
@Traderain Updated package with the fix.

**Comment by Traderain** [comment]
Thanks. It works flawlesly.
