### ISSUE TITLE
File I/O Exception being thrown

### ISSUE THREAD

**Issue by chuckv2014** [ravibpatel/AutoUpdater.NET#242]
Hello, 
 
I have implemented the updater in my code and overall it works... though I am getting an exception error (that may be a Windows error, since it worked “once” and then failed every time going forward). 

Here is the error... something to do with the assembly... if you can help me resolve this it would be much appreciated. I can click “continue” and it loads the updated .exe fine...

Thank you,
Chuck

System.IO.FileNotFoundException: Could not load file or assembly 'AutoUpdaterTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'AutoUpdaterTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at HMS.MDIMain.MDIMain_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ravibpatel** [comment]
@chuckv2014 Are you using NuGet package?

**Comment by chuckv2014** [comment]
No, not that I am aware... only the downloaded code.

**Comment by chuckv2014** [comment]
... I have AutoUpdateNET as a project in my solution... this may be the wrong usage. Should I simply have a reference to the DLL and remov the AutoUpdateNET Project? This is the only place I can think of that is causing the assembly not to be found... obviously not real familiar with this product as yet.

Thank you for your help
Chuck

**Comment by chuckv2014** [comment]
.... ok, removed the AutoUpdateNET project from my solution and referenced the .DLL (that I newly compiled) instead... same thing, looking for the AutoUpdaterNET assembly... stumped as to what I am doing wrong.

Thank you for your help.
Chuck

**Comment by ravibpatel** [comment]
You should use the NuGet package.

**Comment by rrzhaobaojun** [comment]
I also [met] #301 #301 
＃重复
