### ISSUE TITLE
System.Security.SecurityException

### ISSUE THREAD

**Issue by mushramb0** [ravibpatel/AutoUpdater.NET#258]
System.Security.SecurityException: Requested registry access is not allowed.
   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at AutoUpdaterDotNET.UpdateForm.UseLatestIE()
   at AutoUpdaterDotNET.UpdateForm..ctor()
   at AutoUpdaterDotNET.AutoUpdater.ShowUpdateForm()
   at AutoUpdaterDotNET.AutoUpdater.BackgroundWorkerOnRunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs runWorkerCompletedEventArgs)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
The area of the failed assembly is:
MyComputer

**Comment by DjordjeMandic** [comment]
Try adding `AutoUpdater.RunUpdateAsAdmin = true;` before calling start method or run the application as administrator.

**Comment by ravibpatel** [comment]
I will handle the exception there. Thanks for reporting.
