### ISSUE TITLE
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.

### ISSUE THREAD

**Issue by Mecanik** [ravibpatel/AutoUpdater.NET#307]
I am getting this weird error after adding this library to my project. Unfortunately it only happens on 1 PC which runs a fresh installation of Windows 10 Home.

Cannot seem to trace it exactly why this is happening, and it's really weird because I use my own event dialog. My application is also run as administrator so that is out of the question.

Is it possible to disable this translation ? Or just set a specific language ?

**Comment by ravibpatel** [comment]
You can change language as shown in test project.

https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdaterTest/FormMain.cs#L37

Do you have the full stack trace?

**Comment by Mecanik** [comment]
Thank you, I shall test and come back with results.

**Comment by Mecanik** [comment]
I think this is caused because of the obfuscator I am using... https://github.com/obfuscar/obfuscar

I had the same issue with my app, I had to modify the .resx files so the obfuscator would not touch them...

```
************** Exception Text **************
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   at System.Security.AccessControl.ObjectSecurity`1.AddAccessRule(AccessRule`1 rule)
   at  . . ()
   at  . . (Object , EventArgs )
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

**Comment by Mecanik** [comment]
Yeah so the obfuscator renames all .resx files to ".." and it only works if you have 1 .resx file. The dev and the others don't care about this issue, as I have reported it long time ago.

I solved this in my application by removing **ResXFileCodeGenerator** from the .resx properties - could I do this somehow for your library or would I need to compile it myself ?

**Comment by ravibpatel** [comment]
For .NET Framework 4.0 and above library embeds resx files into assembly but it is still causing the problem then you should recompile it.
