### ISSUE TITLE
Not load file or assembly AutoUpdater.NET.XmlSerializers

### ISSUE THREAD

**Issue by Ares-87** [ravibpatel/AutoUpdater.NET#493]
Hi,
I have updated to the latest version 1.70 and now I have this issue, I'm not finding a solution.
Anyone can help me? This is the log generated:

```
---------------------------------------------------
System.IO.FileNotFoundException: Could not load file or assembly 'AutoUpdater.NET.XmlSerializers, Version=1.7.0.0, Culture=neutral, PublicKeyToken=501435c91b35f4bc' or one of its dependencies. Impossibile trovare il file specificato.
File name: 'AutoUpdater.NET.XmlSerializers, Version=1.7.0.0, Culture=neutral, PublicKeyToken=501435c91b35f4bc'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

=== Pre-bind state information ===
LOG: DisplayName = AutoUpdater.NET.XmlSerializers, Version=1.7.0.0, Culture=neutral, PublicKeyToken=501435c91b35f4bc, processorArchitecture=MSIL
 (Fully-specified)
LOG: Appbase = file:///(MY APPLICATION ROOT)/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: (MY APPLICATION ROOT)\bin\Debug\(MY APPLICATION NAME).exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: AutoUpdater.NET.XmlSerializers, Version=1.7.0.0, Culture=neutral, PublicKeyToken=501435c91b35f4bc, processorArchitecture=MSIL
LOG: Attempting download of new URL file:///C:/Users/(MY USERNAME)/source/repos/(MY APPLICATION ROOT)/bin/Debug/AutoUpdater.NET.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Users/(MY USERNAME)/source/repos/(MY APPLICATION ROOT)/bin/Debug/AutoUpdater.NET.XmlSerializers/AutoUpdater.NET.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Users/(MY USERNAME)/source/repos/(MY APPLICATION ROOT)/bin/Debug/AutoUpdater.NET.XmlSerializers.EXE.
LOG: Attempting download of new URL file:///C:/Users/(MY USERNAME)/source/repos/(MY APPLICATION ROOT)/bin/Debug/AutoUpdater.NET.XmlSerializers/AutoUpdater.NET.XmlSerializers.EXE.

---------------------------------------------------
```

**Comment by TrickyShit** [comment]
Have a same issue

**Comment by blufie** [comment]
You have to generate these manually after build using SGEN utiltiy from a command prompt opened form visual studio... I targeted the net45 .dll since thats the one I am using in all my code.  ymmv.  

**c:\Users\<user>\source\repos\autoupdater2\AutoUpdater.NET-master\AutoUpdater.NET\bin\Debug\net45>sgen autoupdater.net.dll
Microsoft (R) Xml Serialization support utility
[Microsoft (R) .NET Framework, Version 4.8.3928.0]
Copyright (C) Microsoft Corporation. All rights reserved.
Serialization Assembly Name: AutoUpdater.NET.XmlSerializers, Version=1.7.1.0, Culture=neutral, PublicKeyToken=null.
Generated serialization assembly for assembly C:\Users\user\source\repos\autoupdater2\AutoUpdater.NET-master\AutoUpdater.NET\bin\Debug\net45\autoupdater.net.dll --> 'C:\Users\user\source\repos\autoupdater2\AutoUpdater.NET-master\AutoUpdater.NET\bin\Debug\net45\AutoUpdater.NET.XmlSerializers.dll'.**
