### ISSUE TITLE
Error accessing private GitHub repo items using personal access token

### ISSUE THREAD

**Issue by iamsubingyawali** [ravibpatel/AutoUpdater.NET#509]
I am trying to access an xml file inside my GitHub private repo. I am using an URL similar to:

https://TOKEN@raw.githubusercontent.com/ORG/REPO/main/update.xml

The URL works fine when accessed using Postman but throws System.Net.WebException 404 when passing through AppUpdater.Start method.

```
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at AutoUpdaterDotNET.AutoUpdater.CheckUpdate(Assembly mainAssembly)
   at AutoUpdaterDotNET.AutoUpdater.<>c.<Start>b__42_0(Object _, DoWorkEventArgs args)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by iamsubingyawali** [comment]
Exception due to underlying HttpClient.
