### ISSUE TITLE
Microsoft.Web.Webview2 latest version breaks auto updater

### ISSUE THREAD

**Issue by bokspro** [ravibpatel/AutoUpdater.NET#547]
If I update Microsoft.Web.Webview2 to version 1.0.1264.42(Latest version) I get exception when I start auto updater:
Method not found: 'System.Threading.Tasks.Task Microsoft.Web.WebView2.WinForms.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)'.
**Stack trace:**
```
   at AutoUpdaterDotNET.UpdateForm.InitializeBrowserControl()
   at AutoUpdaterDotNET.UpdateForm..ctor(UpdateInfoEventArgs args) in c:\projects\AutoUpdater.NET\AutoUpdater.NET\UpdateForm.cs:line 20
   at AutoUpdaterDotNET.AutoUpdater.ShowUpdateForm(UpdateInfoEventArgs args) in c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.cs:line 657
   at AutoUpdaterDotNET.AutoUpdater.StartUpdate(Object result) in c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.cs:line 468
   at AutoUpdaterDotNET.AutoUpdater.<>c.<Start>b__43_1(Object _, RunWorkerCompletedEventArgs args) in c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.cs:line 329
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

```
But downgrading to Microsoft.Web.Webview2 version 1.0.1245.22 fixes the issue.
My project is .Net framework 4.8 windows forms.
This is how I start auto updater:
```
public void CheckUpdates()
        {
            string UpdatePath =  @"\\my-server\update.xml";
            AutoUpdater.Synchronous = false;
            AutoUpdater.RunUpdateAsAdmin = false;
            AutoUpdater.Mandatory = false;
            AutoUpdater.Start(UpdatePath);
        }
```
update.xml contents:
```
<?xml version='1.0' encoding='UTF-8'?>
<item>
    <version>2.0.136.81</version>
    <url>\\my-server\update.zip</url>
    <mandatory>true</mandatory>
</item>
```
To replicate the issue, I created a simple .Net Framework 4.8 windows forms project, added AutoUpdater.NET through nugget, and updated Microsoft.Web.Webview2 to the latest version
[autoupdater_test.zip](https://github.com/ravibpatel/AutoUpdater.NET/files/9061554/autoupdater_test.zip)
:

**Comment by TrucksLOG** [comment]
Remove the changelog entry from your XAML file, then WebView should no longer be displayed. I still have AutoUpdater.UpdateMode = Mode.ForcedDownload; turned on, we do it that way

**Comment by ravibpatel** [comment]
I am investigating the issue. I will post an update once I find the solution.

**Comment by ravibpatel** [comment]
I managed to fix the issue in the latest commit. Can you check it out by manually referencing the DLL from [here](https://ci.appveyor.com/api/buildjobs/qsmuen4fnb2ibvs3/artifacts/AutoUpdater.NET-1.7.4.zip)?

**Comment by bokspro** [comment]
> I managed to fix the issue in the latest commit. Can you check it out by manually referencing the DLL from [here](https://ci.appveyor.com/api/buildjobs/qsmuen4fnb2ibvs3/artifacts/AutoUpdater.NET-1.7.4.zip)?

Thank you, this commit fixed the issue for me!
