### ISSUE TITLE
download error: Illegal characters in path.

### ISSUE THREAD

**Issue by pondkub** [ravibpatel/AutoUpdater.NET#69]
Could you please try using dropbox url? 
I got an error "**Illegal characters in path.**" 
here is a stack trace :

   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at AutoUpdaterDotNET.DownloadUpdateDialog.DownloadUpdateDialogLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

you can try using my url 
[https://www.dropbox.com/s/1ck2iy1jl4hlmbb/latestversion.xml?dl=1](https://www.dropbox.com/s/1ck2iy1jl4hlmbb/latestversion.xml?dl=1)

p.s. I am using Visual Studio 2017

thank you

**Comment by ravibpatel** [comment]
@pondkub You can download the latest build from [here](https://www.dropbox.com/s/rgze0gsijk6q199/AutoUpdater.NET.zip?dl=0).

**Comment by pondkub** [comment]
many thanks for a quick response. I tested it already and it works flawlessly.
happy new year!

**Comment by ravibpatel** [comment]
@pondkub Great. Happy new year to you too!
